#!/usr/bin/env python3
"""Write version_info.txt for PyInstaller from starstack.__version__.

A Windows exe with no version resource (no product name, no company, no
file version) looks, to Defender's heuristics, like something that was
thrown together to be thrown away. This gives starstack.exe a Properties >
Details tab like any other program. Run before `pyinstaller starstack.spec`;
the spec references the file it writes.
"""
import re
import os

here = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(here, "starstack.py"), encoding="utf-8").read()
version = re.search(r'^__version__\s*=\s*"([^"]+)"', src, re.M).group(1)
nums = [int(x) for x in re.findall(r"\d+", version)][:4]
nums += [0] * (4 - len(nums))
tup = tuple(nums)

text = f"""# generated by make_version_info.py from starstack.__version__ -- do not edit
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tup},
    prodvers={tup},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Kyle Fox'),
        StringStruct('FileDescription', 'starstack -- one-button astrophotography stacking'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', 'starstack'),
        StringStruct('LegalCopyright', 'MIT License. https://github.com/kylefoxaustin/starstack'),
        StringStruct('OriginalFilename', 'starstack.exe'),
        StringStruct('ProductName', 'starstack'),
        StringStruct('ProductVersion', '{version}')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
out = os.path.join(here, "version_info.txt")
with open(out, "w", encoding="utf-8") as fh:
    fh.write(text)
print(f"wrote {out} for starstack {version}")
